'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Footer from '../../components/Footer';
import { AccountIcon, BagIcon, HeartIcon, SearchIcon } from '../../components/StoreIcons';
import { hoodies } from '../../lib/hoodies';
import { tshirtProduct } from '../../lib/tshirt';

export default function HoodiesPage() {
  const [searchOpen, setSearchOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [query, setQuery] = useState('');

  useEffect(() => {
    const items = Array.from(document.querySelectorAll<HTMLElement>('[data-reveal]'));
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('reveal-in'); observer.unobserve(entry.target); } }), { threshold: 0.12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);

  const catalog = [
    { id: tshirtProduct.id, href: `/tshirts/${tshirtProduct.id}`, name: tshirtProduct.name, detail: '59 DNT / T-SHIRT', search: `${tshirtProduct.name} white t-shirt oversized drp-ts-003` },
    ...hoodies.map((hoodie) => ({ id: hoodie.id, href: `/hoodies/${hoodie.id}`, name: hoodie.name, detail: `ARCHIVE / ${hoodie.color.toUpperCase()}`, search: `${hoodie.name} ${hoodie.color} hoodie ${hoodie.serial}` })),
  ];
  const matches = catalog.filter((piece) => piece.search.toLowerCase().includes(query.trim().toLowerCase()));
  return <main className="min-h-screen bg-[#f7f7f5] text-black">
    <style jsx global>{`[data-reveal]{opacity:0;transform:translateY(24px);transition:opacity .7s ease,transform .7s cubic-bezier(.2,.7,.2,1)}.reveal-in{opacity:1!important;transform:translateY(0)!important}@media(prefers-reduced-motion:reduce){[data-reveal]{opacity:1;transform:none;transition:none}}`}</style>
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f7f7f5]/95 backdrop-blur-md"><div className="relative mx-auto flex h-16 max-w-[1600px] items-center px-3 sm:px-8 lg:px-12"><nav className="hidden gap-6 md:flex"><Link href="/tshirts" className="text-[9px] font-bold tracking-[.14em]">T-SHIRTS</Link><Link href="/support" className="text-[9px] font-bold tracking-[.14em]">SUPPORT</Link></nav><button onClick={() => setMenuOpen((open) => !open)} aria-expanded={menuOpen} aria-controls="hoodies-mobile-menu" className="w-fit text-[9px] font-bold tracking-[.14em] md:hidden">MENU <span className="ml-1 text-base font-normal leading-none">{menuOpen ? '−' : '+'}</span></button><Link href="/" className="absolute left-1/2 -translate-x-1/2 text-[16px] font-black tracking-[-.08em]">DRIP<span className="font-normal">NALITY</span><sup className="ml-0.5 text-[6px]">&reg;</sup></Link><div className="ml-auto flex items-center gap-1 sm:gap-2"><button onClick={() => { setQuery(''); setSearchOpen(true); }} className="grid size-8 place-items-center" aria-label="Search hoodies"><SearchIcon/></button><Link href="/wishlist" className="grid size-8 place-items-center" aria-label="Saved pieces"><HeartIcon/></Link><Link href="/account" className="grid size-8 place-items-center" aria-label="Account"><AccountIcon/></Link><Link href="/bag" className="flex items-center gap-1 text-[10px] font-bold tracking-[.13em]" aria-label="Shopping bag"><span className="hidden sm:inline">BAG</span><BagIcon/><span>(0)</span></Link></div></div>{menuOpen && <div id="hoodies-mobile-menu" className="absolute inset-x-0 top-full border-b border-black/10 bg-[#f7f7f5] px-5 py-5 shadow-xl md:hidden"><div className="mx-auto flex max-w-[1600px] flex-col"><Link onClick={() => setMenuOpen(false)} href="/tshirts" className="border-b border-black/10 py-4 text-[10px] font-bold tracking-[.15em]">T-SHIRTS <span className="float-right">↗</span></Link><Link onClick={() => setMenuOpen(false)} href="/support" className="border-b border-black/10 py-4 text-[10px] font-bold tracking-[.15em]">SUPPORT <span className="float-right">↗</span></Link></div></div>}</header>

    <section className="relative isolate flex min-h-[590px] items-end overflow-hidden bg-black text-white sm:min-h-[680px]"><Image src="/ds black1.jpg" alt="Black Signature Zip Hoodie editorial" fill priority sizes="100vw" className="object-cover grayscale opacity-70"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,.92),rgba(0,0,0,.46),rgba(0,0,0,.15))]"/><div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.055)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.055)_1px,transparent_1px)] bg-[size:58px_58px] opacity-35"/><div data-reveal className="relative mx-auto w-full max-w-[1600px] px-5 pb-14 sm:px-8 sm:pb-16 lg:px-12 lg:pb-20"><p className="text-[9px] font-bold tracking-[.27em] text-white/65">DRIPNALITY / DROP 01 / ARCHIVE</p><h1 className="mt-6 max-w-4xl text-[clamp(3.6rem,9vw,9.6rem)] font-black leading-[.76] tracking-[-.1em]">THE<br/>FIRST <span className="font-serif font-normal italic tracking-[-.12em]">form.</span></h1><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-[340px] text-[12px] leading-relaxed text-white/65">Two limited zip hoodies built as the opening chapter of DRIPNALITY. Preserved here as an archive, not a restock.</p><a href="#archive" className="inline-flex w-fit items-center gap-4 border-b border-white/70 pb-3 text-[10px] font-bold uppercase tracking-[.16em]">Explore the archive <span>↓</span></a></div></div></section>

    <section id="archive" className="mx-auto max-w-[1500px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div data-reveal className="flex flex-col justify-between gap-7 border-b border-black/10 pb-7 md:flex-row md:items-end"><div><p className="eyebrow">ARCHIVE / 02 PIECES</p><h2 className="mt-4 text-[clamp(2.8rem,6vw,6.6rem)] font-black leading-[.81] tracking-[-.09em]">SOLD OUT.<br/><span className="font-serif font-normal italic tracking-[-.11em]">Still present.</span></h2></div><p className="max-w-xs text-[12px] leading-relaxed text-black/55">The first release is closed. Both pieces remain visible as a record of the collection&apos;s original proportions and finish.</p></div><div className="mt-12 grid gap-x-6 gap-y-14 md:grid-cols-2">{hoodies.map((hoodie,index)=><article data-reveal key={hoodie.id} className="group"><Link href={`/hoodies/${hoodie.id}`} className="relative block aspect-[4/5] overflow-hidden bg-[#e9e9e6]"><Image src={hoodie.listingImage} alt={hoodie.name} fill priority={index===0} sizes="(max-width:768px) 100vw,50vw" className="object-cover transition duration-700 ease-out group-hover:scale-[1.025]"/><span className="absolute left-4 top-4 bg-white px-3 py-2 text-[9px] font-bold tracking-[.14em]">0{index+1} / ARCHIVE</span><span className="absolute inset-x-4 bottom-4 flex items-center justify-between bg-white/95 px-4 py-3 text-[9px] font-bold tracking-[.13em]">VIEW PIECE <span>↗</span></span></Link><div className="mt-5 grid grid-cols-[1fr_auto] gap-5"><div><p className="text-[9px] font-bold tracking-[.14em] text-black/45">{hoodie.serial}</p><h3 className="mt-2 text-[14px] font-bold uppercase">{hoodie.name}</h3><p className="mt-1 text-[10px] text-black/50">{hoodie.color} / Sold out</p></div><p className="text-[12px] font-bold">{hoodie.price} TND</p></div></article>)}</div></section>

    <section data-reveal className="grid overflow-hidden bg-black text-white lg:grid-cols-2"><div className="relative min-h-[470px]"><Image src="/ds brown1.jpg" alt="Brown archive hoodie editorial" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover grayscale"/></div><div className="flex min-h-[470px] flex-col justify-between p-8 sm:p-12 lg:p-16"><div><p className="eyebrow text-white/60">DESIGNED WITH PURPOSE</p><h2 className="mt-5 text-[clamp(3.2rem,5.7vw,6.5rem)] font-black leading-[.82] tracking-[-.09em]">FORM<br/>FOLLOWS<br/><span className="font-serif font-normal italic tracking-[-.1em]">feeling.</span></h2></div><div className="max-w-sm"><p className="text-[13px] leading-relaxed text-white/65">We focus on proportion, weight and the details you feel before anyone sees them. A uniform for moving through the world with intent.</p><Link href="/tshirts" className="mt-8 inline-flex border-b border-white pb-2 text-[10px] font-bold tracking-[.14em]">EXPLORE CURRENT RELEASE <span className="ml-10">→</span></Link></div></div></section>
    <section className="relative min-h-[520px] overflow-hidden bg-black text-white sm:min-h-[640px]"><video className="absolute inset-0 h-full w-full object-cover opacity-75" autoPlay loop muted playsInline preload="metadata" poster="/ds brown1.jpg"><source src="/vid brown22.mp4" type="video/mp4"/></video><div className="absolute inset-0 bg-black/45"/><div data-reveal className="relative mx-auto flex min-h-[520px] max-w-[1500px] flex-col justify-end px-5 py-12 sm:min-h-[640px] sm:px-8 lg:px-12 lg:py-16"><p className="text-[9px] font-bold tracking-[.25em] text-white/65">MOTION ARCHIVE / BROWN 02</p><h2 className="mt-5 max-w-3xl text-[clamp(3rem,7vw,7.6rem)] font-black leading-[.8] tracking-[-.1em]">FORM, HELD<br/><span className="font-serif font-normal italic tracking-[-.11em]">in motion.</span></h2></div></section><Footer/>
    {searchOpen && <><button className="fixed inset-0 z-50 bg-black/35 backdrop-blur-sm" onClick={()=>setSearchOpen(false)} aria-label="Close search"/><section role="dialog" aria-modal="true" aria-label="Search the collection" className="fixed inset-x-3 top-3 z-[51] mx-auto max-w-2xl bg-white p-5 shadow-2xl sm:top-8 sm:p-8"><div className="flex border-b border-black"><SearchIcon className="my-3 size-5 shrink-0"/><input autoFocus value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search pieces, colours or categories" className="w-full bg-transparent px-3 py-3 text-xl outline-none"/><button onClick={()=>setSearchOpen(false)} className="text-[10px] font-bold tracking-[.14em]">CLOSE</button></div><p className="mt-4 text-[9px] font-bold tracking-[.14em] text-black/45">{query.trim() ? `${matches.length} RESULT${matches.length === 1 ? '' : 'S'}` : 'ALL PIECES'}</p><div className="mt-2">{matches.length ? matches.map((piece)=><Link onClick={()=>setSearchOpen(false)} href={piece.href} key={piece.id} className="flex items-center justify-between gap-5 border-b border-black/10 py-4 text-sm font-bold transition hover:pl-2"><span>{piece.name}</span><span className="shrink-0 text-[9px] tracking-[.12em] text-black/55">{piece.detail} ↗</span></Link>) : <p className="border-b border-black/10 py-8 text-sm text-black/55">No pieces match “{query}”. Try T-shirt, black, brown or oversized.</p>}</div></section></>}
  </main>;
}
