import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { hoodies } from '../../../lib/hoodies';
import { AccountIcon, BagIcon, HeartIcon, SearchIcon } from '../../../components/StoreIcons';

export default async function HoodieDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const hoodie = hoodies.find((item) => item.id === slug);
  if (!hoodie) notFound();
  return (
    <main className="min-h-screen bg-[#f7f7f5] text-black">
      <header className="sticky top-0 z-30 border-b border-black/10 bg-[#f7f7f5]/95 backdrop-blur-md"><div className="relative mx-auto flex h-16 max-w-[1600px] items-center px-3 sm:px-8 lg:px-12"><nav className="hidden gap-6 md:flex"><Link href="/hoodies" className="text-[9px] font-bold tracking-[.14em]">HOODIES</Link><Link href="/support" className="text-[9px] font-bold tracking-[.14em]">SUPPORT</Link></nav><Link href="/" className="absolute left-1/2 -translate-x-1/2 text-[15px] font-black tracking-[-.08em]">DRIP<span className="font-normal">NALITY</span><sup className="ml-0.5 text-[6px]">&reg;</sup></Link><div className="ml-auto flex items-center gap-1 sm:gap-2"><Link href="/hoodies" className="grid size-8 place-items-center" aria-label="Search archive"><SearchIcon/></Link><Link href="/wishlist" className="grid size-8 place-items-center" aria-label="Saved pieces"><HeartIcon/></Link><Link href="/account" className="grid size-8 place-items-center" aria-label="Account"><AccountIcon/></Link><Link href="/bag" className="flex items-center gap-1 text-[10px] font-bold tracking-[.13em]" aria-label="Shopping bag"><span className="hidden sm:inline">BAG</span><BagIcon/><span>(0)</span></Link></div></div></header>
      <section className="mx-auto max-w-[1560px] px-3 py-3 sm:px-6 sm:py-6 lg:grid lg:grid-cols-[minmax(0,1.2fr)_minmax(340px,.8fr)] lg:gap-10 lg:px-10 lg:py-10">
        <div className="grid gap-3 sm:grid-cols-2">{hoodie.gallery.map((image, index) => <figure key={image} className="relative aspect-[4/5] overflow-hidden bg-[#e9e9e6]"><Image src={image} alt={`${hoodie.name}, view ${index + 1}`} fill priority={index < 2} sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 42vw" className="object-cover" /><figcaption className="absolute bottom-3 left-3 bg-white/90 px-2.5 py-1.5 text-[8px] font-bold tracking-[.14em]">ARCHIVE / {String(index + 1).padStart(2, '0')}</figcaption></figure>)}</div>
        <aside className="px-3 py-10 sm:px-5 lg:sticky lg:top-16 lg:h-fit lg:px-0 lg:py-3"><p className="eyebrow">DRIPNALITY / DROP 01</p><div className="mt-3 flex justify-between text-[10px] font-bold tracking-[.14em] text-black/45"><span>{hoodie.serial}</span><span>SOLD OUT</span></div><h1 className="mt-7 text-[clamp(2.8rem,5vw,5.2rem)] font-black leading-[.79] tracking-[-.09em] uppercase">{hoodie.name}</h1><p className="mt-6 text-[16px] font-bold">{hoodie.price} TND</p><p className="mt-6 max-w-md text-sm leading-6 text-black/60">{hoodie.description}</p><dl className="mt-8 grid grid-cols-2 gap-x-5 gap-y-5 border-y border-black/10 py-5 text-[10px] font-bold uppercase tracking-[.12em]"><div><dt className="text-black/45">Release</dt><dd className="mt-1">Drop 01</dd></div><div><dt className="text-black/45">Status</dt><dd className="mt-1">Archive / Sold out</dd></div></dl><div className="mt-8"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.15em]">Archive sizing</p><div className="flex gap-2">{['S', 'M', 'L'].map((size) => <span key={size} className="grid size-12 place-items-center border border-black/15 text-[11px] font-bold text-black/35 line-through">{size}</span>)}</div></div><div className="mt-8 flex w-full items-center justify-between bg-black/35 px-5 py-4 text-[10px] font-bold uppercase tracking-[.16em] text-white">Sold out / Archive piece <span>&mdash;</span></div><Link href="/tshirts" className="mt-4 inline-block text-[10px] font-bold uppercase tracking-[.14em] underline underline-offset-4">Explore current release</Link></aside>
      </section>
    </main>
  );
}
